baseURL: "https://www.merveaydar.com"
languageCode: "en-us"
title: "Merve Aydar"
theme: hugo-profile
pluralizelisttitles: false
Paginate: 3
disqusShortname: #gurusabarish
googleAnalytics: G-V0SVR4S6DQ

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Yazılar
      title: Yazılar
      url: /yazı
      weight: 1
    
    # - identifier: terapi
    #   name: Terapi
    #   title: Terapi Hakkında Bilgiler
    #   url: /terapi
    #   weight: 2

    # # Dropdown menu
    # - identifier: dropdown
    #   title: Terapi
    #   name: Terapi
    #   weight: 3
    # - identifier: dropdown1
    #   title: Terapiye Başlama
    #   name: Terapiye Başlama
    #   url: /terapiye-baslama
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: Gizlilik
    #   name: Gizlilik
    #   url: /gizlilik
    #   parent: dropdown
    #   weight: 2
    # - identifier: dropdown3
    #   title: Onam
    #   name: Onam
    #   url: /onam
    #   parent: dropdown
    #   weight: 3

params:
  title: "Klinik Psikolog Merve Aydar"
  description: Klinik Psikolog Merve Aydar
  # staticPath: ""  # The path to serve the static files from
  favicon: /images/icon.png

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  #color preference
  #color:
    #textColor: 
    #secondaryTextColor: "#9A90AB"
    #backgroundColor:
    #secondaryBackgroundColor:
    #primaryColor:
    #secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Merhabalar, ben"
    title: "Merve Aydar"
    subtitle: "Klinik Psikolog"
    content: "Çocuk, Ergen ve Yetişkin Ruh sağlığı alanında çalışmalar yapmaktayım. 2 yıldır aktif bir şekilde danışan görmekteyim. Destekleyici Terapi alanında yoğunlaşıyorum."
    image: /images/mervee.png
    button:
      enable: true
      name: "Özgeçmiş"
      url: /UzmPskMerveAydar_Ozgecmis.pdf
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-instagram
          url: https://www.instagram.com/uzm.psk.merveaydar/
        - icon: fa fa-envelope
          url: mailto:merveeaydar@gmail.com
        # - icon: fab fa-twitter
        #   url: https://twitter.com
        # - icon: fab fa-github
        #   url: https://github.com/merveaydar
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "Hakkımda"
    image: /images/merve_cool.jpeg
    content: |-
      Beykent Üniversitesi Psikoloji bölümünden 2020 yılında mezun oldum. Aynı sene Arel Üniversitesi Klinik Psikoloji Yüksek Lisans programına kabul aldım ve Yıldız Teknik Üniversitesi’nden Aile Danışmanlığı eğitimimi aldım. 2022 Şubat ayında 3.53 ortalama ile Klinik Psikoloji Yüksek Lisansımı tamamladım. Uzmanlık eğitimim boyunca Destekleyici-Psikodinamik ekoller ağırlıklı olarak 3 dönem süpervizyon aldım. Fransız Lape Hastanesi, Aktüel Psikolojik Araştırmalar Merkezi ve Mavi Hospital’de stajlarımı yaptım.  İki sene boyunca seans ve süpervizyonlarımın kazandırdığı terapistlik deneyimi, aktif dinleme ve destekleyici biçimde problem çözme konusunda kendimi geliştirmeme yardımcı oldu. Ek olarak danışanlarımın kişisel gelişimi ve takibi konularında da deneyim kazandım. Yetişkinlerle destekleyici-psikodinamik temelli bir klinik yaklaşımı benimseyerek terapi çalışmalarımı sürdürmekte olup kendi terapi sürecimden de geçmekteyim. 
    skills:
      enable: false
      title: "ilgilendiğim psiko şeysileri"
      items:
        - "destekleyici terapi"
        - "destekleyici"
        - "terapi"

  # Experience
  experience:
    enable: true
    items:
      - job: "Klinik Psikolog"
        company: |
          Bi' Şey Seans
        companyUrl: "https://biseyseans.com/"
        date: "2022 - Halen"
        featuredLink:
          enable: true
          url: "https://biseyseans.com/ogrenci-seans-destek-projesi/"
        info:
          enable: true
          content: Gönüllülük kapsamında öğrencilere yardım amaçlı düşük ücretli terapi hizmeti.
        content: |
          "Öğrenci Seans Destek" Projesi kapsamında dezavantajlı öğrencilere uygun fiyatta terapi hizmeti sağlamaktayım. Proje kapsamında hem online hem de yüzyüze danışan almaktayım.

      - job: "Stajyer Psikolog"
        company: "Mavi Hospital"
        companyUrl: "https://mavihospital.com/"
        date: "2021"
        info:
          enable: true
          content: Zorunlu staj dahilinde 2 aylık bir süreçte tamamladım.
        featuredLink:
          enable: false
        content: |
          Akhisar, Manisa'da bulunan özel Mavi Hospital'de stajımı tamamladım.

          - Klinik psikoloğun terapi seanslarında bulunduğu rolü, kullandığı yöntem ve teknikleri gözlemledim.

      - job: "Stajyer Psikolog"
        company: "Aktüel Psikolojik Araştırmalar Merkezi"
        companyUrl: "http://www.apamer.com.tr/"
        date: "2019 - 2020"
        info:
          enable: false
        featuredLink:
          enable: false
        content: |
          - Her yaş grubundan danışanlar ile ön görüşme, gözlem ve vaka analizleri yapma fırsatı buldum. 
          - Farklı ekollerden uzmanlarla vaka tartışmaları yaptım. Her ekolün nasıl çalıştığı ile ilgili bilgiler edindim.
          - Terapi süreçlerini planlama ve formülasyon oluşturma konusunda deneyim sahibi oldum.
          - Psikolojik test ve ölçeklerin uygulanmasına yardımcı olarak ve gözlemleyerek öğrendim.


      - job: "Stajyer Psikolog"
        company: "Fransız Lape Hastanesi"
        companyUrl: "https://www.fransizlape.com/"
        date: "2019"
        featuredLink:
          enable: false
          name: "Deneyimlerim"
          url: /yazı/lape
        content: |
          - Müzik terapisi ve sanat terapisi atölyelerinde hastaları gözlemledim ve bu atölyelerde etkin rol aldım.
          - Günaydın toplantılarıyla uzman psikologlar eşliğinde yatan hastaların durumları hakkında bilgi edindim. 
          - Kapalı, geriatri ve amatem servisinde pek çok hasta ile iletişime geçip onlar ile çeşitli aktiviteler yaptım.

  # Education
  education:
    enable: false
    # index: true
    items:
      - title: "Master of Business Administration"
        school:
          name: "University of California, Berkeley"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Massachusetts Institute of Technology"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Thomas Jefferson High School for Science and Technology."
          url: "https://example.org"
        GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: false
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: |- 
      Bana her zaman aşağıdaki formu doldurarak ya da mail adresimden ulaşabilirsiniz.
      
      <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdBVHtsE7UFSdfB7eezSCeGDW-5o1iRfkG1SXcXTcY_vBI9AA/viewform?embedded=true" width="800" height="1000" frameborder="0" marginheight="0" marginwidth="0">Yükleniyor…</iframe>
      
    email: merveeaydar@gmail.com
    btnName: Mail Atabilirsiniz

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/merveaydar
      linkedin: https://linkedin.com/in/merveaydar
      #twitter: https://twitter.com
      instagram: https://www.instagram.com/uzm.psk.merveaydar/
      #facebook: https://facebook.com
